services:
  mentores_backend:
    image: ${CONTAINER_IMAGE}
    container_name: mentores_backend
    restart: always
    networks:
      - traefik
      - database
    env_file:
      - .env
    environment:
      - TYPEORM_HOST=database_soujunior
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vagas-backend.rule=Host(`mentores-backend.soujunior.tech`)"
      - "traefik.http.routers.vagas-backend.entrypoints=websecure"
      - "traefik.http.routers.vagas-backend.tls.certresolver=myresolver"
      - "traefik.http.services.vagas-backend.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.traefik-headers.headers.sslredirect=true"
      - "traefik.http.middlewares.traefik-headers.headers.sslforcehost=true"
      - "traefik.http.middlewares.traefik-headers.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.docker.network=traefik"

networks:
  database:
    external: true
  traefik:
    external: true
