version: '3.9'

services:
  database_soujunior:
    image: postgres
    container_name: database_soujunior
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=mentores_backend
    volumes:
      - pgdata:/data/postgres
  mentores_backend:
    build: .
    container_name: mentores_backend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database_soujunior
    depends_on:
      - database_soujunior
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://docker:ignite@mentores_backend:3306/mentores_backend?reconnect=true

volumes:
  pgdata:
    driver: local
