name: Renovate
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/staging.yml
        with:
          branch_name: ${{ env.NAME }}
      - uses: renovatebot/renovate@27.23.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
